services:
  db:
    image: bitnami/postgresql:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db
