import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <SidebarProvider>
          <div className="flex w-full min-h-screen">
            <AppSidebar />
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
